#!/usr/bin/env python3
"""
asm_data_to_c.py — mechanical converter for the labeled `db 0x.., 0x..`
sprite/data files under data/*.asm into C headers.

This does NOT interpret what the bytes mean (that's the job of the game
logic ported later, e.g. alley_drawing.asm / objects.asm which know how
to read *_ptrs / *_dims tables and feed them to the cga.c blit routines).
It just faithfully preserves each labeled region as a byte array, 1:1,
so nothing is lost or reinterpreted incorrectly by hand-transcription.

Usage: python3 asm_data_to_c.py <input.asm> <output.h> <header_guard_prefix>
"""
import re
import sys

LABEL_RE = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*):\s*$')
DB_RE = re.compile(r'db\s+((?:0x[0-9a-fA-F]{2}\s*,?\s*)+)')
BYTE_RE = re.compile(r'0x([0-9a-fA-F]{2})')

def parse(path):
    """Returns list of (label, bytearray) in file order. Bytes before the
    first label go into a synthetic '_leading' region."""
    regions = []
    cur_label = "_leading"
    cur_bytes = bytearray()

    with open(path, "r") as f:
        for line in f:
            line = line.rstrip("\n")
            m = LABEL_RE.match(line)
            if m:
                regions.append((cur_label, cur_bytes))
                cur_label = m.group(1)
                cur_bytes = bytearray()
                continue
            m = DB_RE.search(line)
            if m:
                for b in BYTE_RE.findall(m.group(1)):
                    cur_bytes.append(int(b, 16))
        regions.append((cur_label, cur_bytes))

    # drop empty leading region if nothing before first label
    regions = [(n, b) for (n, b) in regions if len(b) > 0]
    return regions

def emit_header(regions, out_path, guard):
    with open(out_path, "w") as f:
        f.write(f"/* Auto-generated by asm_data_to_c.py — DO NOT EDIT BY HAND.\n")
        f.write(f" * Mechanically extracted from the original disassembly's\n")
        f.write(f" * data/*.asm, one C array per labeled region, byte-for-byte\n")
        f.write(f" * identical to the original db data. */\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n#include <stdint.h>\n#include <stddef.h>\n\n")
        names = []
        for name, data in regions:
            f.write(f"static const uint8_t {name}[] = {{\n")
            for i in range(0, len(data), 16):
                chunk = data[i:i+16]
                f.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
            f.write("};\n")
            f.write(f"static const size_t {name}_len = sizeof({name});\n\n")
            names.append(name)
        f.write(f"#endif /* {guard} */\n")
    return names

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)
    in_path, out_path, guard = sys.argv[1], sys.argv[2], sys.argv[3]
    regions = parse(in_path)
    names = emit_header(regions, out_path, guard)
    total = sum(len(b) for _, b in regions)
    print(f"{in_path}: {len(names)} regions, {total} bytes -> {out_path}")
    for n, b in regions:
        print(f"    {n}: {len(b)} bytes")
