#!/usr/bin/env python3
"""
embed_data_segment.py — embeds the fully-verified, byte-exact
reconstruction of the game's ENTIRE data segment (/tmp/data_segment.bin,
28976 bytes, produced by resolve_data_segment.py) as a C byte array.

Why: draw_block_list (alley_drawing.asm) and draw_level_background
(score.asm) address background/level-room tile source data via ARBITRARY
ABSOLUTE DS OFFSETS, not through a clean per-sprite pointer table like
every other sprite category in this project. Since the offsets are
scattered and interleaved with code-adjacent data throughout the segment,
extracting each tile individually by name isn't practical or necessary —
instead, this ships the whole verified segment as one "tile pool" that
draw_block_list can index into exactly the way the original does,
preserving the same addressing scheme byte-for-byte. See PROGRESS.md
Sec 5w.
"""
with open("/tmp/data_segment.bin", "rb") as f:
    data = f.read()

out_path = "/home/claude/alleycat-c/include/gen/ds_pool.h"
c_path = "/home/claude/alleycat-c/src/gen_ds_pool.c"

with open(out_path, "w") as f:
    f.write("/* Auto-generated by embed_data_segment.py — DO NOT EDIT.\n")
    f.write(" * The full, verified, byte-exact reconstruction of the\n")
    f.write(f" * original's .data segment ({len(data)} bytes) — see\n")
    f.write(" * PROGRESS.md Sec 5w for why this is embedded wholesale\n")
    f.write(" * rather than extracted tile-by-tile. Index directly with\n")
    f.write(" * the same absolute DS offsets the original assembly uses. */\n")
    f.write("#ifndef DS_POOL_H\n#define DS_POOL_H\n\n#include <stdint.h>\n#include <stddef.h>\n\n")
    f.write(f"#define DS_POOL_SIZE {len(data)}\n")
    f.write("extern const uint8_t ds_pool[DS_POOL_SIZE];\n\n#endif\n")

with open(c_path, "w") as f:
    f.write("/* Auto-generated by embed_data_segment.py — DO NOT EDIT. */\n")
    f.write("#include \"gen/ds_pool.h\"\n\n")
    f.write(f"const uint8_t ds_pool[DS_POOL_SIZE] = {{\n")
    for j in range(0, len(data), 20):
        f.write("    " + ", ".join(f"0x{b:02x}" for b in data[j:j+20]) + ",\n")
    f.write("};\n")

print(f"Embedded {len(data)} bytes -> {out_path}, {c_path}")
