#!/usr/bin/env python3
"""
extract_death_sprite.py — extracts death_sprite (the cat's falling-death
"splat" pose) using its verified size (5 words x 18 rows = 180 bytes,
confirmed against draw_alley_foreground's `mov cx,0x1205` call site and
cross-checked to end exactly at the start of the gravity_sprite chain —
see PROGRESS.md Sec 5i/5j). Drawn via blit_transparent (color-keyed,
black=transparent), now fixed — see cga.c.
"""
with open("/tmp/data_segment.bin", "rb") as f:
    data = f.read()
labels = {}
with open("/tmp/data_segment_labels.txt") as f:
    for line in f:
        off_s, name = line.strip().split("\t")
        labels[name] = int(off_s, 16)

off = labels["death_sprite"]
W_WORDS, H = 5, 18
size = W_WORDS * 2 * H
sprite = data[off:off+size]
print(f"death_sprite: DS {off:#06x}, {W_WORDS}w x {H}h ({size}B)")

out_path = "/home/claude/alleycat-c/include/gen/death_sprite.h"
c_path = "/home/claude/alleycat-c/src/gen_death_sprite.c"

with open(out_path, "w") as f:
    f.write("/* Auto-generated by extract_death_sprite.py — DO NOT EDIT.\n")
    f.write(" * The cat's falling-death pose, drawn via blit_transparent\n")
    f.write(" * (black = transparent, any other color = opaque). See\n")
    f.write(" * PROGRESS.md Sec 5i/5j for how the size was verified and how\n")
    f.write(" * blit_transparent's real semantics were derived. */\n")
    f.write("#ifndef DEATH_SPRITE_H\n#define DEATH_SPRITE_H\n\n#include \"../sprite.h\"\n\n")
    f.write("extern const cat_walk_frame_t death_sprite_frame;\n\n#endif\n")

with open(c_path, "w") as f:
    f.write("/* Auto-generated by extract_death_sprite.py — DO NOT EDIT. */\n")
    f.write("#include \"gen/death_sprite.h\"\n\n")
    f.write("static const uint8_t death_sprite_data[] = {\n")
    for j in range(0, len(sprite), 16):
        f.write("    " + ", ".join(f"0x{b:02x}" for b in sprite[j:j+16]) + ",\n")
    f.write("};\n\n")
    f.write(f"const cat_walk_frame_t death_sprite_frame = "
            f"{{ death_sprite_data, {W_WORDS}, {H} }};\n")

print(f"Wrote {out_path} and {c_path}")
