#!/usr/bin/env python3
"""
extract_level_geometry.py — extracts the door and platform geometry
tables used by check_door_position/check_level_platform, verified by
walking each level's sentinel-terminated list end-to-end (see
PROGRESS.md Sec 5n).
"""
import struct

with open("/tmp/data_segment.bin", "rb") as f:
    data = f.read()
labels = {}
with open("/tmp/data_segment_labels.txt") as f:
    for line in f:
        off_s, name = line.strip().split("\t")
        labels[name] = int(off_s, 16)

# --- doors ---
dpt_off = labels["door_position_table"]
ffd_off = labels["floor_first_door"]
fdc_off = labels["floor_door_count"]
door_position_table = list(data[dpt_off:dpt_off+22])
floor_first_door = list(data[ffd_off:ffd_off+8])
floor_door_count = list(data[fdc_off:fdc_off+8])

# sanity: every difficulty's door list (starting at floor_first_door[diff],
# scanning door_position_table until a 0x00 sentinel byte — NOT using
# floor_door_count, which check_door_position doesn't consult at all;
# it's used elsewhere, e.g. to randomly pick a target door) terminates
# within the table.
for diff in range(8):
    start = floor_first_door[diff]
    bx = start
    steps = 0
    while door_position_table[bx] != 0:
        bx += 1
        steps += 1
        assert bx < len(door_position_table), f"difficulty {diff} door list ran off the table"
        assert steps < 30, f"difficulty {diff} door list didn't terminate"
print("door tables verified: all 8 difficulty lists terminate with sentinel 0x00")

# --- platforms ---
lpi_off = labels["level_platform_index"]
y_off = labels["platform_y_table"]
type_off = labels["platform_type_table"]
width_off = labels["platform_width_table"]
xleft_off = labels["platform_x_left"]

level_platform_index = list(struct.unpack_from("<8H", data, lpi_off))
TABLE_SIZE = 96
platform_y_table = list(data[y_off:y_off+TABLE_SIZE])
platform_type_table = list(data[type_off:type_off+TABLE_SIZE])
platform_width_table = list(struct.unpack_from(f"<{TABLE_SIZE}H", data, width_off))
platform_x_left = list(struct.unpack_from(f"<{TABLE_SIZE}H", data, xleft_off))

max_bx = 0
for lvl, start_bx in enumerate(level_platform_index):
    bx = start_bx
    steps = 0
    while platform_y_table[bx] != 0:
        max_bx = max(max_bx, bx)
        bx += 1
        steps += 1
        assert steps < 60, f"level {lvl} platform list didn't terminate"
print(f"platform tables verified: all 8 level lists terminate, max index used = {max_bx}")

out_path = "/home/claude/alleycat-c/include/gen/level_geometry.h"
c_path = "/home/claude/alleycat-c/src/gen_level_geometry.c"

with open(out_path, "w") as f:
    f.write("/* Auto-generated by extract_level_geometry.py — DO NOT EDIT.\n")
    f.write(" * Door and platform geometry tables for check_door_position/\n")
    f.write(" * check_level_platform. Verified by walking every level/\n")
    f.write(" * difficulty's sentinel-terminated list end-to-end — see\n")
    f.write(" * PROGRESS.md Sec 5n. */\n")
    f.write("#ifndef LEVEL_GEOMETRY_H\n#define LEVEL_GEOMETRY_H\n\n#include <stdint.h>\n\n")
    f.write("extern const uint8_t door_position_table[22];\n")
    f.write("extern const uint8_t floor_first_door[8];\n")
    f.write("extern const uint8_t floor_door_count[8];\n")
    f.write("extern const uint16_t level_platform_index[8];\n")
    f.write(f"extern const uint8_t platform_y_table[{TABLE_SIZE}];\n")
    f.write(f"extern const uint8_t platform_type_table[{TABLE_SIZE}];\n")
    f.write(f"extern const uint16_t platform_width_table[{TABLE_SIZE}];\n")
    f.write(f"extern const uint16_t platform_x_left[{TABLE_SIZE}];\n\n#endif\n")

def emit_byte_array(f, name, vals):
    f.write(f"const uint8_t {name}[{len(vals)}] = {{ " + ", ".join(str(v) for v in vals) + " };\n")

def emit_word_array(f, name, vals):
    f.write(f"const uint16_t {name}[{len(vals)}] = {{ " + ", ".join(str(v) for v in vals) + " };\n")

with open(c_path, "w") as f:
    f.write("/* Auto-generated by extract_level_geometry.py — DO NOT EDIT. */\n")
    f.write("#include \"gen/level_geometry.h\"\n\n")
    emit_byte_array(f, "door_position_table", door_position_table)
    emit_byte_array(f, "floor_first_door", floor_first_door)
    emit_byte_array(f, "floor_door_count", floor_door_count)
    emit_word_array(f, "level_platform_index", level_platform_index)
    emit_byte_array(f, "platform_y_table", platform_y_table)
    emit_byte_array(f, "platform_type_table", platform_type_table)
    emit_word_array(f, "platform_width_table", platform_width_table)
    emit_word_array(f, "platform_x_left", platform_x_left)

print(f"\nWrote {out_path} and {c_path}")
