#!/usr/bin/env python3
"""
extract_object_sprites.py — extracts the 3 object sprites from
object_sprites.asm using sizes verified against real objects.asm call
sites (see PROGRESS.md Sec 5k/5l):
  - collision_sprite: cx=0x806 (8w x 6h = 96B), blit_transparent
  - cycle_idle_sprite: cx=0x802 (2w x 8h = 32B), blit_masked
  - cycle_walk_sprite: 4 frames of 32B each (confirmed by the repo's own
    ASCII-art annotations matching a mouse walk cycle), followed by 96
    bytes of verified all-zero padding (not sprite data).
"""
with open("/tmp/data_segment.bin", "rb") as f:
    data = f.read()
labels = {}
with open("/tmp/data_segment_labels.txt") as f:
    for line in f:
        off_s, name = line.strip().split("\t")
        labels[name] = int(off_s, 16)

pieces = []

off = labels["collision_sprite"]
pieces.append(("collision_sprite_frame", off, 8, 6, data[off:off+8*2*6]))

off = labels["cycle_idle_sprite"]
pieces.append(("cycle_idle_sprite_frame", off, 2, 8, data[off:off+2*2*8]))

base = labels["cycle_walk_sprite"]
for i in range(4):
    off = base + i * 32
    pieces.append((f"cycle_walk_sprite_frame_{i}", off, 2, 8, data[off:off+32]))

for name, off, w, h, b in pieces:
    print(f"{name}: DS {off:#06x}, {w}w x {h}h ({len(b)}B)")

out_path = "/home/claude/alleycat-c/include/gen/object_sprites_ex.h"
c_path = "/home/claude/alleycat-c/src/gen_object_sprites.c"

with open(out_path, "w") as f:
    f.write("/* Auto-generated by extract_object_sprites.py — DO NOT EDIT.\n")
    f.write(" * collision_sprite (drawn via the now-fixed blit_transparent),\n")
    f.write(" * cycle_idle_sprite, and cycle_walk_sprite's 4 walk-cycle frames\n")
    f.write(" * (a mouse enemy, per the disassembly repo's own ASCII-art\n")
    f.write(" * comments in data/object_sprites.asm). See PROGRESS.md Sec 5k/5l\n")
    f.write(" * for how sizes were verified against real objects.asm call sites.\n")
    f.write(" * NOTE: collision_sprite has a further 28 bytes of real (non-zero,\n")
    f.write(" * patterned) data immediately after this frame that isn't\n")
    f.write(" * referenced by name anywhere in the currently-read source —\n")
    f.write(" * not included here, left as an open question (see PROGRESS.md). */\n")
    f.write("#ifndef OBJECT_SPRITES_EX_H\n#define OBJECT_SPRITES_EX_H\n\n#include \"../sprite.h\"\n\n")
    f.write("extern const cat_walk_frame_t collision_sprite_frame;\n")
    f.write("extern const cat_walk_frame_t cycle_idle_sprite_frame;\n")
    f.write("extern const cat_walk_frame_t cycle_walk_sprite_frames[4];\n\n#endif\n")

with open(c_path, "w") as f:
    f.write("/* Auto-generated by extract_object_sprites.py — DO NOT EDIT. */\n")
    f.write("#include \"gen/object_sprites_ex.h\"\n\n")
    for name, off, w, h, b in pieces:
        f.write(f"static const uint8_t {name}_data[] = {{\n")
        for j in range(0, len(b), 16):
            f.write("    " + ", ".join(f"0x{x:02x}" for x in b[j:j+16]) + ",\n")
        f.write("};\n\n")
    f.write("const cat_walk_frame_t collision_sprite_frame = "
            "{ collision_sprite_frame_data, 8, 6 };\n")
    f.write("const cat_walk_frame_t cycle_idle_sprite_frame = "
            "{ cycle_idle_sprite_frame_data, 2, 8 };\n")
    f.write("const cat_walk_frame_t cycle_walk_sprite_frames[4] = {\n")
    for i in range(4):
        f.write(f"    {{ cycle_walk_sprite_frame_{i}_data, 2, 8 }},\n")
    f.write("};\n")

print(f"\nWrote {out_path} and {c_path}")
