#!/usr/bin/env python3
"""
extract_enemy_sprites.py — extracts the dog enemy's sprite frames from
enemy_sprite_table (11 word entries, indices 0-7 meaningfully used per
update_enemy_sprite's bitfield index math — see PROGRESS.md Sec 5i/5o).
Size verified exactly against pointer-table deltas: all consecutive
unique pointers are spaced exactly 120 bytes apart, matching
update_enemy_viewport's base dims (cx=0xf04 -> 4 words x 15 rows = 120B).
"""
import struct

with open("/tmp/data_segment.bin", "rb") as f:
    data = f.read()
labels = {}
with open("/tmp/data_segment_labels.txt") as f:
    for line in f:
        off_s, name = line.strip().split("\t")
        labels[name] = int(off_s, 16)

ptrs_off = labels["enemy_sprite_table"]
ptrs = struct.unpack_from("<11H", data, ptrs_off)

W_WORDS, H = 4, 15
SIZE = W_WORDS * 2 * H

used = ptrs[:8]
print("enemy_sprite_table[0..7]:", [hex(p) for p in used])

unique_ptrs = {}
for i, p in enumerate(used):
    if p not in unique_ptrs:
        b = data[p:p+SIZE]
        unique_ptrs[p] = b
        print(f"  new frame at slot {i}: DS {p:#06x} ({SIZE}B)")
    else:
        print(f"  slot {i}: DS {p:#06x} (reuses frame already seen)")

out_path = "/home/claude/alleycat-c/include/gen/enemy_sprites_ex.h"
c_path = "/home/claude/alleycat-c/src/gen_enemy_sprites.c"

with open(out_path, "w") as f:
    f.write("/* Auto-generated by extract_enemy_sprites.py — DO NOT EDIT.\n")
    f.write(" * The dog enemy's 7 unique sprite frames (4w x 15h = 120B\n")
    f.write(" * each, verified exactly against enemy_sprite_table's pointer\n")
    f.write(" * deltas — see PROGRESS.md Sec 5i/5o). Indices 0-3 (word-offsets\n")
    f.write(" * 0,2,4,6) are the 2-frame x 2-direction walk cycle; indices 4-7\n")
    f.write(" * (word-offsets 8,10,12,14) are the 4-frame 'caught the cat'\n")
    f.write(" * animation (index 5 and 7 share the same underlying frame).\n")
    f.write(" * Drawn via blit_transparent per draw_enemy's real call site. */\n")
    f.write("#ifndef ENEMY_SPRITES_EX_H\n#define ENEMY_SPRITES_EX_H\n\n#include \"../sprite.h\"\n\n")
    f.write("extern const cat_walk_frame_t enemy_sprite_frames[8]; /* index = word-offset/2, matches enemy_sprite_ptr */\n\n#endif\n")

names = {}
for i, p in enumerate(unique_ptrs):
    names[p] = f"enemy_sprite_frame_{i}"

with open(c_path, "w") as f:
    f.write("/* Auto-generated by extract_enemy_sprites.py — DO NOT EDIT. */\n")
    f.write("#include \"gen/enemy_sprites_ex.h\"\n\n")
    for p, b in unique_ptrs.items():
        f.write(f"static const uint8_t {names[p]}_data[] = {{\n")
        for j in range(0, len(b), 16):
            f.write("    " + ", ".join(f"0x{x:02x}" for x in b[j:j+16]) + ",\n")
        f.write("};\n\n")
    f.write("const cat_walk_frame_t enemy_sprite_frames[8] = {\n")
    for i, p in enumerate(used):
        f.write(f"    {{ {names[p]}_data, {W_WORDS}, {H} }}, /* slot {i}, DS {p:#06x} */\n")
    f.write("};\n")

print(f"\nWrote {out_path} and {c_path}")
