#!/usr/bin/env python3
"""
extract_walk_sprites.py — uses the verified data segment (data_segment.bin)
plus the resolved DS offsets of walk_sprite_ptrs/walk_sprite_dims to slice
out each of the 13 walk-cycle cat sprite frames as individual, correctly-
bounded C byte arrays (rather than one big unlabeled 730-byte blob).
"""
import struct

with open("/tmp/data_segment.bin", "rb") as f:
    data = f.read()

labels = {}
with open("/tmp/data_segment_labels.txt") as f:
    for line in f:
        off_s, name = line.strip().split("\t")
        labels[name] = int(off_s, 16)

ptrs_off = labels["walk_sprite_ptrs"]
dims_off = labels["walk_sprite_dims"]
NUM_FRAMES = 13

ptrs = struct.unpack_from(f"<{NUM_FRAMES}H", data, ptrs_off)
dims = [(data[dims_off + i*2], data[dims_off + i*2 + 1]) for i in range(NUM_FRAMES)]

frames = []
for i, (ptr, (w_words, h)) in enumerate(zip(ptrs, dims)):
    # w_words is a WORD count (verified against pointer-table deltas: every
    # frame boundary lines up exactly under width_words*2*height, with zero
    # gap/overlap across the whole 13-frame set). Real byte width = w_words*2.
    w_bytes = w_words * 2
    size = w_bytes * h
    frame_bytes = data[ptr:ptr+size]
    frames.append((i, ptr, w_words, h, frame_bytes))
    print(f"frame {i:2d}: DS offset {ptr:#06x}, {w_words}w x {h}h "
          f"({w_bytes}B/row, {size}B total) -> {len(frame_bytes)}B read")

out_path = "/home/claude/alleycat-c/include/gen/cat_walk_frames.h"
c_path = "/home/claude/alleycat-c/src/gen_cat_walk_frames.c"
with open(out_path, "w") as f:
    f.write("/* Auto-generated by extract_walk_sprites.py — DO NOT EDIT.\n")
    f.write(" * 13 walk-cycle cat sprite frames, sliced from the verified\n")
    f.write(" * data segment using resolved DS pointer/dims tables (see\n")
    f.write(" * tools/resolve_data_segment.py). width_words is a WORD count\n")
    f.write(" * (verified against pointer-table deltas: real bytes/row =\n")
    f.write(" * width_words*2); height = scanlines. Pass width_words directly\n")
    f.write(" * to cga.c's blit_*() functions, which expect the same unit.\n")
    f.write(" * Definitions live in src/gen_cat_walk_frames.c (single shared\n")
    f.write(" * instance — extern here so pointer identity is consistent\n")
    f.write(" * across every translation unit that includes this header). */\n")
    f.write("#ifndef CAT_WALK_FRAMES_H\n#define CAT_WALK_FRAMES_H\n\n#include <stdint.h>\n#include \"../sprite.h\"\n\n")
    f.write("extern const cat_walk_frame_t cat_walk_frames[13];\n\n#endif\n")

with open(c_path, "w") as f:
    f.write("/* Auto-generated by extract_walk_sprites.py — DO NOT EDIT. */\n")
    f.write("#include \"gen/cat_walk_frames.h\"\n\n")
    for i, ptr, w, h, b in frames:
        f.write(f"static const uint8_t cat_walk_frame_{i}_data[] = {{\n")
        for j in range(0, len(b), 16):
            chunk = b[j:j+16]
            f.write("    " + ", ".join(f"0x{x:02x}" for x in chunk) + ",\n")
        f.write("};\n\n")
    f.write("const cat_walk_frame_t cat_walk_frames[13] = {\n")
    for i, ptr, w, h, b in frames:
        f.write(f"    {{ cat_walk_frame_{i}_data, {w}, {h} }}, /* DS {ptr:#06x} */\n")
    f.write("};\n")

print(f"\nWrote {out_path} and {c_path}")
