#!/usr/bin/env python3
"""
extract_gap1_sprites.py — extracts the "gap 1" sprites (DS 0x0a2e-0x0bd2):
enter_sprite_data (5 ptrs, some reusing Pool B), climb_sprite_ptrs (1 ptr),
recoil_sprite_ptrs (8 ptrs, 2 of which reuse Pool B frames directly).
Every pointer's predicted end (width_words*2*height) was cross-checked
against the next pointer/known Pool B frame start with zero slack before
writing this script — see PROGRESS.md §5d.
"""
import struct

with open("/tmp/data_segment.bin", "rb") as f:
    data = f.read()
labels = {}
with open("/tmp/data_segment_labels.txt") as f:
    for line in f:
        off_s, name = line.strip().split("\t")
        labels[name] = int(off_s, 16)

POOL_B_PTRS = set(struct.unpack_from("<12H", data, labels["walk_frame_table"]))

def read_table(ptr_label, dim_label, count):
    ptrs = struct.unpack_from(f"<{count}H", data, labels[ptr_label])
    dims = [(data[labels[dim_label]+i*2], data[labels[dim_label]+i*2+1]) for i in range(count)]
    return list(zip(ptrs, dims))

enter = read_table("enter_sprite_data", "enter_sprite_dims", 5)
climb = read_table("climb_sprite_ptrs", "climb_sprite_dims", 1)
recoil = read_table("recoil_sprite_ptrs", "recoil_sprite_dims_tbl", 8)

# de-dup unique sprites by pointer (some entries across tables share a ptr)
unique = {}
for ptr, (w, h) in enter + climb + recoil:
    if ptr in POOL_B_PTRS:
        continue  # already have this one from Pool B
    unique.setdefault(ptr, (w, h))

print(f"{len(unique)} unique new sprites found in gap 1 (+ {len(set(p for p,_ in enter+climb+recoil) & POOL_B_PTRS)} reused from Pool B)")
sprite_names = {}
for i, ptr in enumerate(sorted(unique)):
    w, h = unique[ptr]
    size = w * 2 * h
    sprite_names[ptr] = f"gap1_sprite_{i}"
    print(f"  {sprite_names[ptr]}: DS {ptr:#06x}, {w}w x {h}h ({size}B)")

out_path = "/home/claude/alleycat-c/include/gen/cat_gap1_sprites.h"
c_path = "/home/claude/alleycat-c/src/gen_cat_gap1_sprites.c"

with open(out_path, "w") as f:
    f.write("/* Auto-generated by extract_gap1_sprites.py — DO NOT EDIT.\n")
    f.write(" * The 6 distinct sprites found in the previously-unaccounted\n")
    f.write(" * 'gap 1' (DS 0x0a2e-0x0bd2) — see PROGRESS.md §5d for the full\n")
    f.write(" * derivation. enter_sprite[] = 'entering window/door' poses,\n")
    f.write(" * climb_sprite = single climbing pose, recoil_sprite[] = new\n")
    f.write(" * knockback poses (the recoil animation ALSO reuses 2 frames\n")
    f.write(" * directly from cat_walk_frames — see recoil_uses_pool_b_frame\n")
    f.write(" * indices below, callers should fall back to cat_walk_frames\n")
    f.write(" * for those instead of anything in this file). */\n")
    f.write("#ifndef CAT_GAP1_SPRITES_H\n#define CAT_GAP1_SPRITES_H\n\n#include <stdint.h>\n#include \"../sprite.h\"\n\n")
    f.write("extern const cat_walk_frame_t enter_sprite[5];\n")
    f.write("extern const cat_walk_frame_t climb_sprite;\n")
    f.write("extern const cat_walk_frame_t recoil_sprite[8]; /* NULL data ptr for entries that reuse a Pool B frame */\n")
    f.write("extern const uint16_t recoil_pool_b_frame_index[8]; /* valid only where recoil_sprite[i].data==NULL; index into cat_walk_frames-equivalent Pool B array (0xFFFF = n/a) */\n\n#endif\n")

with open(c_path, "w") as f:
    f.write("/* Auto-generated by extract_gap1_sprites.py — DO NOT EDIT. */\n")
    f.write("#include \"gen/cat_gap1_sprites.h\"\n#include \"gen/cat_alley_walk_frames.h\"\n#include <stddef.h>\n\n")
    for ptr in sorted(unique):
        w, h = unique[ptr]
        b = data[ptr:ptr+w*2*h]
        f.write(f"static const uint8_t {sprite_names[ptr]}_data[] = {{\n")
        for j in range(0, len(b), 16):
            f.write("    " + ", ".join(f"0x{x:02x}" for x in b[j:j+16]) + ",\n")
        f.write("};\n\n")

    def emit_array(varname, entries, count):
        f.write(f"const cat_walk_frame_t {varname}[{count}] = {{\n")
        for ptr, (w, h) in entries:
            if ptr in POOL_B_PTRS:
                f.write(f"    {{ NULL, 0, 0 }}, /* reuses a Pool B frame (DS {ptr:#06x}) — see cat_alley_walk_frames.h */\n")
            else:
                f.write(f"    {{ {sprite_names[ptr]}_data, {w}, {h} }}, /* DS {ptr:#06x} */\n")
        f.write("};\n\n")

    emit_array("enter_sprite", enter, 5)
    w, h = climb[0][1]
    f.write(f"const cat_walk_frame_t climb_sprite = {{ {sprite_names[climb[0][0]]}_data, {w}, {h} }};\n\n")
    emit_array("recoil_sprite", recoil, 8)

    f.write("const uint16_t recoil_pool_b_frame_index[8] = {\n")
    pool_b_list = list(struct.unpack_from("<12H", data, labels["walk_frame_table"]))
    for ptr, _ in recoil:
        idx = pool_b_list.index(ptr) if ptr in POOL_B_PTRS else 0xFFFF
        f.write(f"    {idx},\n")
    f.write("};\n")

print(f"\nWrote {out_path} and {c_path}")
