#!/usr/bin/env python3
"""
extract_fall_sprite.py — extracts fall_sprite (the falling/dropped-object
dodge mechanic in objects.asm's animate_falling), verified as exactly
2 words x 13 rows = 52 bytes (the max height ever used; height varies
1..13..0 frame-to-frame reading fewer/more rows from this SAME fixed
52-byte block — see PROGRESS.md Sec 5u). Zero slack against the next
label (fall_save_buf).
"""
with open("/tmp/data_segment.bin", "rb") as f:
    data = f.read()
labels = {}
with open("/tmp/data_segment_labels.txt") as f:
    for line in f:
        off_s, name = line.strip().split("\t")
        labels[name] = int(off_s, 16)

off = labels["fall_sprite"]
W_WORDS, MAX_H = 2, 13
SIZE = W_WORDS * 2 * MAX_H
sprite = data[off:off+SIZE]
print(f"fall_sprite: DS {off:#06x}, {W_WORDS}w x {MAX_H}h max ({SIZE}B)")

out_path = "/home/claude/alleycat-c/include/gen/fall_sprite.h"
c_path = "/home/claude/alleycat-c/src/gen_fall_sprite.c"

with open(out_path, "w") as f:
    f.write("/* Auto-generated by extract_fall_sprite.py — DO NOT EDIT.\n")
    f.write(" * The falling-object dodge mechanic's sprite (objects.asm's\n")
    f.write(" * animate_falling). Fixed width (2 words), but the ORIGINAL\n")
    f.write(" * varies how many rows it blits frame-to-frame (1..13 rising,\n")
    f.write(" * 13..0 falling) from this SAME 52-byte block — pass a\n")
    f.write(" * variable height to blit_transparent rather than always using\n")
    f.write(" * the full 13. See PROGRESS.md Sec 5u. */\n")
    f.write("#ifndef FALL_SPRITE_H\n#define FALL_SPRITE_H\n\n#include <stdint.h>\n\n")
    f.write(f"extern const uint8_t fall_sprite_data[{SIZE}];\n\n#endif\n")

with open(c_path, "w") as f:
    f.write("/* Auto-generated by extract_fall_sprite.py — DO NOT EDIT. */\n")
    f.write("#include \"gen/fall_sprite.h\"\n\n")
    f.write(f"const uint8_t fall_sprite_data[{SIZE}] = {{\n")
    for j in range(0, len(sprite), 16):
        f.write("    " + ", ".join(f"0x{b:02x}" for b in sprite[j:j+16]) + ",\n")
    f.write("};\n")

print(f"Wrote {out_path} and {c_path}")
