#!/usr/bin/env python3
"""
extract_digit_sprites.py — extracts the 10 shared digit sprites (0-9)
used by both the score display (render_score_digits) and the lives
counter (draw_lives). Each digit: cx=0x801 -> 1 word wide x 8 rows = 16B.
Functionally only 10 entries are ever indexed (BCD digits 0-9); a further
224 unexplained bytes follow before the next real label (alley_base_block_list)
— not chased further, see PROGRESS.md Sec 5v.
"""
with open("/tmp/data_segment.bin", "rb") as f:
    data = f.read()
labels = {}
with open("/tmp/data_segment_labels.txt") as f:
    for line in f:
        off_s, name = line.strip().split("\t")
        labels[name] = int(off_s, 16)

off = labels["digit_sprites"]
N, W_WORDS, H = 10, 1, 8
SIZE_EACH = W_WORDS * 2 * H
sprites = data[off:off + N * SIZE_EACH]

out_path = "/home/claude/alleycat-c/include/gen/digit_sprites.h"
c_path = "/home/claude/alleycat-c/src/gen_digit_sprites.c"

with open(out_path, "w") as f:
    f.write("/* Auto-generated by extract_digit_sprites.py — DO NOT EDIT.\n")
    f.write(" * The 10 shared digit sprites (0-9), 1 word x 8 rows each,\n")
    f.write(" * used by both the score display and the lives counter.\n")
    f.write(" * See PROGRESS.md Sec 5v. */\n")
    f.write("#ifndef DIGIT_SPRITES_H\n#define DIGIT_SPRITES_H\n\n#include <stdint.h>\n\n")
    f.write(f"extern const uint8_t digit_sprite_data[{N * SIZE_EACH}]; /* digit N at offset N*{SIZE_EACH} */\n\n#endif\n")

with open(c_path, "w") as f:
    f.write("/* Auto-generated by extract_digit_sprites.py — DO NOT EDIT. */\n")
    f.write("#include \"gen/digit_sprites.h\"\n\n")
    f.write(f"const uint8_t digit_sprite_data[{N * SIZE_EACH}] = {{\n")
    for j in range(0, len(sprites), 16):
        f.write("    " + ", ".join(f"0x{b:02x}" for b in sprites[j:j+16]) + ",\n")
    f.write("};\n")

print(f"Extracted {N} digit sprites ({SIZE_EACH}B each) -> {out_path}, {c_path}")
