#!/usr/bin/env python3
"""
extract_obj_hit_sprites.py — extracts the 3 "hit reaction" sprite frames
for the alley's 3 cycling patrol objects (rats/mice), used by
objects.asm's check_cycle_cat_collision (cx=0x802 -> 2w x 8h = 32B each,
drawn via blit_transparent).

This ALSO resolves PROGRESS.md Sec 5l's open question about the 28
unexplained bytes after collision_sprite: obj_hit_sprite's own pointer
table (DS 0x1f5f, 3 words) points at 0x1dd0/0x1df0/0x1e10 — i.e. directly
into that "mystery" region right after collision_sprite (which ends at
0x1dd0). Diffing those 3 pointers gives exactly 32 bytes each, and the
last one ends exactly at cycle_idle_sprite's start (0x1e30) — zero gap,
same rigor as every other sprite table in this project. So the "28-byte
tail" was never padding OR a stray 4th collision_sprite variant: it's the
first bytes of 3 legitimate, fully-accounted-for hit-reaction sprites
that just happen to sit immediately after collision_sprite in the data
segment, auto-labeled together by the disassembler exactly like every
other split-label case documented in Sec 3/Sec 5i/Sec 7.

Also resolves obj_save_buf: previously assumed (from a stale reading) to
span 12 bytes/6 pointers overlapping obj_hit_sprite; re-checking against
the call site's `shl bl,1` (word-indexed by 3 slots) shows the REAL
obj_save_buf is only the first 6 bytes at DS 0x1f59 (3 words: 0x1ed0,
0x1ef0, 0x1f10 — original DOS scratch RAM addresses, not meaningful in
this port, which uses its own C arrays instead), and obj_hit_sprite
starts immediately after at 0x1f5f — again zero gap, same pattern.
"""
with open("/tmp/data_segment.bin", "rb") as f:
    data = f.read()
labels = {}
with open("/tmp/data_segment_labels.txt") as f:
    for line in f:
        off_s, name = line.strip().split("\t")
        labels[name] = int(off_s, 16)

collision_end = labels["collision_sprite"] + 8 * 2 * 6
cycle_idle_start = labels["cycle_idle_sprite"]
assert collision_end == 0x1dd0, hex(collision_end)
assert cycle_idle_start == 0x1e30, hex(cycle_idle_start)

# obj_hit_sprite pointer table: DS 0x1f5f, 3 words (real region, per the
# corrected slicing described above)
ptr_table_off = 0x1f5f
ptrs = []
for i in range(3):
    lo = data[ptr_table_off + i * 2]
    hi = data[ptr_table_off + i * 2 + 1]
    ptrs.append(lo | (hi << 8))

print("obj_hit_sprite pointers:", [hex(p) for p in ptrs])
assert ptrs == [0x1e10, 0x1df0, 0x1dd0], ptrs

# Cross-check: sorted, each consecutive gap is exactly 32B, and the run
# starts exactly at collision_sprite's end and ends exactly at
# cycle_idle_sprite's start.
sorted_ptrs = sorted(ptrs) + [cycle_idle_start]
assert sorted_ptrs[0] == collision_end, sorted_ptrs
for a, b in zip(sorted_ptrs, sorted_ptrs[1:]):
    assert b - a == 32, (hex(a), hex(b))
print("Verified: 3 x 32B frames, zero gap from collision_sprite to cycle_idle_sprite.")

pieces = []
for i, off in enumerate(ptrs):
    pieces.append((f"obj_hit_sprite_frame_{i}", off, 2, 8, data[off:off + 32]))

for name, off, w, h, b in pieces:
    print(f"{name}: DS {off:#06x}, {w}w x {h}h ({len(b)}B)")

out_path = "/home/claude/work/alleycat-c-sdl/alleycat-c-sdl/include/gen/obj_hit_sprites.h"
c_path = "/home/claude/work/alleycat-c-sdl/alleycat-c-sdl/src/gen_obj_hit_sprites.c"

with open(out_path, "w") as f:
    f.write("/* Auto-generated by extract_obj_hit_sprites.py — DO NOT EDIT.\n")
    f.write(" * obj_hit_sprite[3]: knockback/hit-reaction pose for each of the\n")
    f.write(" * alley's 3 cycling patrol objects (rats/mice), drawn via\n")
    f.write(" * blit_transparent when the cat collides with one (objects.asm\n")
    f.write(" * check_cycle_cat_collision). See PROGRESS.md for how this also\n")
    f.write(" * resolved Sec 5l's open \"28-byte tail\" question. */\n")
    f.write("#ifndef OBJ_HIT_SPRITES_H\n#define OBJ_HIT_SPRITES_H\n\n#include \"../sprite.h\"\n\n")
    f.write("extern const cat_walk_frame_t obj_hit_sprite_frames[3];\n\n#endif\n")

with open(c_path, "w") as f:
    f.write("/* Auto-generated by extract_obj_hit_sprites.py — DO NOT EDIT. */\n")
    f.write("#include \"gen/obj_hit_sprites.h\"\n\n")
    for name, off, w, h, b in pieces:
        f.write(f"static const uint8_t {name}_data[] = {{\n")
        for j in range(0, len(b), 16):
            f.write("    " + ", ".join(f"0x{x:02x}" for x in b[j:j+16]) + ",\n")
        f.write("};\n\n")
    f.write("const cat_walk_frame_t obj_hit_sprite_frames[3] = {\n")
    for i in range(3):
        f.write(f"    {{ obj_hit_sprite_frame_{i}_data, 2, 8 }},\n")
    f.write("};\n")

print(f"\nWrote {out_path} and {c_path}")
