#!/usr/bin/env python3
"""
extract_walk_frame_table.py — extracts the second cat animation pool
(walk_frame_table's 12-frame cycle, used in game_loop.asm's "in alley /
entering building" contexts) plus the single fixed climb/enter sprite
that immediately precedes it in the data segment (DS 0x9da, dims 0x0e03,
hardcoded directly in game_loop.asm rather than looked up via a table).

Both use the verified WORD-width convention (real bytes/row = width_field*2).
"""
import struct

with open("/tmp/data_segment.bin", "rb") as f:
    data = f.read()

labels = {}
with open("/tmp/data_segment_labels.txt") as f:
    for line in f:
        off_s, name = line.strip().split("\t")
        labels[name] = int(off_s, 16)

# --- 12-frame walk_frame_table cycle: uniform dims (3 words, 11 rows) ---
# (0x0b03 as used at game_loop.asm's second update_walk_frame call site,
# right before its draw_alley_foreground call)
wft_off = labels["walk_frame_table"]
NUM = 12
ptrs = struct.unpack_from(f"<{NUM}H", data, wft_off)
W_WORDS, H = 3, 11
FRAME_SIZE = W_WORDS * 2 * H

frames = []
for i, ptr in enumerate(ptrs):
    b = data[ptr:ptr+FRAME_SIZE]
    frames.append((i, ptr, b))
    print(f"alley_walk frame {i:2d}: DS {ptr:#06x}, {W_WORDS}w x {H}h "
          f"({FRAME_SIZE}B) -> {len(b)}B read")

# --- fixed "climbing into window/door" sprite, DS 0x9da, dims 0x0e03 ---
CLIMB_OFF = 0x9da
CLIMB_W_WORDS, CLIMB_H = 3, 14
climb_size = CLIMB_W_WORDS * 2 * CLIMB_H
climb_bytes = data[CLIMB_OFF:CLIMB_OFF+climb_size]
print(f"climb/enter sprite: DS {CLIMB_OFF:#06x}, {CLIMB_W_WORDS}w x {CLIMB_H}h "
      f"({climb_size}B) -> {len(climb_bytes)}B read")

out_path = "/home/claude/alleycat-c/include/gen/cat_alley_walk_frames.h"
c_path = "/home/claude/alleycat-c/src/gen_cat_alley_walk_frames.c"
with open(out_path, "w") as f:
    f.write("/* Auto-generated by extract_walk_frame_table.py — DO NOT EDIT.\n")
    f.write(" * 12-frame 'walking in the alley / entering building' cat cycle\n")
    f.write(" * (src/alley.asm update_walk_frame + walk_frame_table), plus the\n")
    f.write(" * single fixed climb/enter sprite at DS 0x9da used directly by\n")
    f.write(" * game_loop.asm when at_platform==1. Verified against pointer\n")
    f.write(" * deltas (all exactly 66 bytes apart == 3 words * 2 * 11 rows).\n")
    f.write(" * width_words is a WORD count — pass directly to cga.c blit_*().\n")
    f.write(" * Definitions in src/gen_cat_alley_walk_frames.c — extern here\n")
    f.write(" * so pointer identity is consistent across translation units. */\n")
    f.write("#ifndef CAT_ALLEY_WALK_FRAMES_H\n#define CAT_ALLEY_WALK_FRAMES_H\n\n#include <stdint.h>\n#include \"../sprite.h\"\n\n")
    f.write("extern const cat_walk_frame_t alley_walk_frames[12];\n")
    f.write("extern const cat_walk_frame_t cat_climb_enter_sprite;\n\n#endif\n")

with open(c_path, "w") as f:
    f.write("/* Auto-generated by extract_walk_frame_table.py — DO NOT EDIT. */\n")
    f.write("#include \"gen/cat_alley_walk_frames.h\"\n\n")
    for i, ptr, b in frames:
        f.write(f"static const uint8_t alley_walk_frame_{i}_data[] = {{\n")
        for j in range(0, len(b), 16):
            f.write("    " + ", ".join(f"0x{x:02x}" for x in b[j:j+16]) + ",\n")
        f.write("};\n\n")
    f.write("const cat_walk_frame_t alley_walk_frames[12] = {\n")
    for i, ptr, b in frames:
        f.write(f"    {{ alley_walk_frame_{i}_data, {W_WORDS}, {H} }}, /* DS {ptr:#06x} */\n")
    f.write("};\n\n")

    f.write("static const uint8_t cat_climb_enter_sprite_data[] = {\n")
    for j in range(0, len(climb_bytes), 16):
        f.write("    " + ", ".join(f"0x{x:02x}" for x in climb_bytes[j:j+16]) + ",\n")
    f.write("};\n")
    f.write(f"const cat_walk_frame_t cat_climb_enter_sprite = "
            f"{{ cat_climb_enter_sprite_data, {CLIMB_W_WORDS}, {CLIMB_H} }};\n")

print(f"\nWrote {out_path} and {c_path}")
